### ISSUE TITLE
Doesn't work with Merlin

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_inline_test#1]
at least out of box :) 

Merlin reports a code, that uses this extension as an error:

```
ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib) 
```

I suspect, that the same result would be for other inliners, i.e., ppx_expect and ppx_benchmark. 

Currently we have two ways to pass ppx options to `ocamlmerlin`:
1. via `FLG -ppx` but this option is kind of broken, as we can pass only one word after the ppx, everything else, is considered as `ocamlmerlin` option (I will report this to upstream)
2. via `PKG name`, where package `name` has a META file with `ppx` and `ppxopt` fields. 

It looks like the latter is default and expected way to use ppx in merlin (and hence better supported). So a good solution for this issue would be to add dummy package `ppx_inliner.libname.for_merlin` that will automatically disable libname checking (or add "dummy" libname). It would be also a good idea for the merlin to pass `"merlin"` predicate, when it performs lookup, so that this dummy library, can be chosen automatically. 
## Temporal workaround

Maybe this information would be useful, for those who come after me. As a temporal workaround, I put in the search path a file `ppx-bap` with the following contents:

```
ppx-jane -as-ppx -inline-test-lib bap $@
```

And then I put option:

```
FLG -ppx ppx-bap
```

into my `.merlin` file.

**Comment by trefis** [comment]
You can also just have `FLG -ppx 'ppx-jane -as-ppx -inline-test-lib bap'` in your `.merlin` (i.e. without an extra file indirection).

As for having passing the right default info in the META and having a merlin predicate it seems to me like a reasonable idea, we'll look into doing it for the next release (but might not depending on how much it complicates the META).

**Comment by ivg** [comment]
Ah, thanks, I've tried to use the quotes, but delimited arguments incorrectly :)

**Comment by copy** [comment]
I got this library working using jbuilder, but the same issue arises. However, in this case I can't edit the merlin file since it's generated by jbuilder.

I don't think jbuilder should have hard-coded infos about ppx libraries, can this issue be fixed in this project? (for example by somehow detecting the presence of merlin and skipping this error in that case.)

**Comment by copy** [comment]
This is now fixed, see https://jbuilder.readthedocs.io/en/latest/tests.html, with the caveat that it may break if one uses more than one library or executable in a the same directory with different flags (https://github.com/ocaml/dune/issues/230).

Cheers everyone!

**Comment by diml** [comment]
Indeed, I'm closing this ticket then.

The caveat is indeed annoying, I hope that we can solve it one day.

**Comment by abliss** [comment]
Maybe I'm misunderstanding, but this seems to be broken again. I get the same error message as the OP. If I manually add `-as-ppx -inline-test-lib bap` to my `.merlin` file, then it works, but it gets overwritten the next time I run `dune`.

Here's my `dune` file:
```
(library
  (name sum)
  (inline_tests)
  (preprocess (pps ppx_inline_test)))
```

**Comment by jeremiedimino** [comment]
Indeed, we discussed this issue [here](https://github.com/janestreet/ppx_expect/issues/26). It was due to a bug in ppxlib, which has now been fixed in master.
