### ISSUE TITLE
Example requires ppx_jane

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/ppx_inline_test#10]
The example defined in this repo requires ppx_jane which in turn requires ppx_inline_test. This makes the example pretty difficult to build since you need both ppx_jane and ppx_inline_test from findlib or both in your jbuild workspace. It would be nicer if the example only required ppx_inline_test.

**Comment by sliquister** [comment]
A few years later, do you still care about this? If you do, is the dependency of the examples on `core` also a problem? (since core depends on `ppx_inline_test` too, since it uses `ppx_jane`).

**Comment by rgrinberg** [comment]
No, it no longer matters to me.
