### ISSUE TITLE
v0.12.0 is incompatible with let operator syntax

### ISSUE THREAD

**Issue by shonfeder** [janestreet/ppx_inline_test#18]
The currently released version is pinned to the previously released version of ppxlib, which seems to be incompatible with the `let` operator syntax added in OCaml 4.08. As a result, attempts to build projects using the released version of this package result in something like

```
Fatal error: exception File "lib/lib.ml", line 30, characters 2-6: let operators are not supported before OCaml 4.08
```

I can see work is underway to put together release v0.13.0, but wanted to note this problem for the record, as it took me some time to debug and figure out the source of the problem.

(Incidentally, I think this is occurring on other Jane Street packages as well, at least including `ppx_sexp_conv`. I expect this will be a problem for all packages that haven't yet cut new releases to increment to the latest `ppxlib`.)

**Comment by hhugo** [comment]
@xclerc, when is the next official release (v0.13.0 ?) planned ?

**Comment by xclerc** [comment]
@hhugo  I am not aware of any plans regarding v0.13.0.
@shonfeder Do we expect the issue to be fixed by simply
bumping the AST version in ppxlib?

**Comment by yminsky** [comment]
Releases should be roughly every six months. So we should go back to when
0.12 was released, and count forward by 6...

**Comment by xclerc** [comment]
(We announced 0.12 on March 14.)

**Comment by shonfeder** [comment]
@xclerc I currently have master pinned and it's working. 

iirc, the AST version in ppxlib is already bumped, and master here (and other Jane Street ppx) has already bumped its version of ppxlib. So, it seems that to address *this* issue, a release just needs to be cut, no additional work done beyond that.

**Comment by sliquister** [comment]
This is sufficiently old that I'm going to assume this got fixed as a result of the normal upgrade/releases.
