### ISSUE TITLE
Anonymous arguments doesn't work with merlin

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_inline_test#2]
This is a very minor issue, but still worthwhile to report. 

If run via `ppx_jane -as-ppx` anonymous tests yield the following messages:

```
Extension `test' was not translated.
Hint: `test' is available for structure items but is used here in the context of an expression. Did you put it at the wrong level?
```
The same is for `test_modules`.

If run via `ppx` we just fail with
```
Uninterpreted extension 'test_module'.
```

**Comment by diml** [comment]
Could you give an example of code that produces these errors?

**Comment by ivg** [comment]
Ok, it looks like that the issue is somehow related with `ocamlmerlin` when I just run the same file with 
```
ocamlbuild -pkg ppx_jane -tag "ppx(ppx-jane -as-ppx -inline-test-lib dummy)" anon.byte
```
it works fine with anonymous tests

**Comment by trefis** [comment]
Yes this is a known merlin bug.
We're working on a fix but you can open an issue on [the-lambda-church/merlin](http://github.com/the-lambda-church/merlin) so I don't forget if you want.
