### ISSUE TITLE
Error using `ppx_inline_test.0.11.0` with `dune>=2.0.0`

### ISSUE THREAD

**Issue by gabrielhdt** [janestreet/ppx_inline_test#20]
Hello,
Using `ppx_inline_test` version `0.11.0` with `dune` version `2.3.0` yields the following error message

> ```
> File "/home/travis/.opam/4.04.1/lib/ppx_inline_test/ppx_inline_test.dune", line 1, characters 0-0:
> Warning: .dune files are ignored since 2.0. Reinstall the library with dune
> >= 2.0 to get rid of this warning and enable support for the subsystem this
> library provides.
> File "src/pure/dune", line 4, characters 1-15:
> 4 |  (inline_tests)
>      ^^^^^^^^^^^^^^
> Error: No inline tests backend found.
> ```

while using with `dune` version `1.11.4` works.

**Comment by hartmut27** [comment]
using `ppx_inline_test` `v0.13.1` with `ocaml-base-compiler.4.10.0`, 
same result unfortunately: 

> file "backend/dune", line 6, characters 13-28:
> 6 |         (pps ppx_inline_test)
>                  ^^^^^^^^^^^^^^^
> Error: Library "ppx_inline_test" not found.
> Hint: try:
> dune external-lib-deps --missing --only-packages fullstack-reason @@default
> error: command failed: 'dune' 'build' '--only-packages' 'fullstack-reason' (exited with 1)
> esy-build-package: exiting with errors above...
> error: build failed with exit code: 1
>   
> esy: exiting due to errors above
>

**Comment by sliquister** [comment]
@hartmut27 it sounds like you need to `opam install ppx_inline_test`, it's not clear it's the same problem as the initial comment.

@gabrielhdt Can you give a full reduced example? Just following what the documentation says works fine for me:

```sh
$ cat dune
(library
 (name foo)
 (inline_tests)
 (preprocess (pps ppx_inline_test))
 )
$ cat foo.ml
let%test _ = false
$ dune build @runtest
File "foo.ml", line 1, characters 0-18: <<false>> is false.

FAILED 1 / 1 tests
```

**Comment by sliquister** [comment]
I'll close this. If someone runs into a similar looking issue and sees this, please open a new issue with reproducible steps.
