### ISSUE TITLE
Name suffix for test modules

### ISSUE THREAD

**Issue by christopher-dG** [janestreet/ppx_inline_test#27]
With ppx_bench's inline benchmark modules, you can set a name suffix ([example](https://github.com/janestreet/ppx_bench/blob/eff66b39bd5370306ad31a06737e38360796198e/example/ppx_bench_sample.ml#L84-L105)).

It seems there's no way to do something similar with this package. Would it be possible to add that feature?

**Comment by sliquister** [comment]
I'm not fond of the way ppx_bench does this, but having dynamic names seems reasonable. I have a change going through review to support `let%test [%name any-expr-of-type-string] = true` instead.

**Comment by aalekseyev** [comment]
This change landed in 4ad759e0d454fba07007901f5221214cb4cd8cd5.
