### ISSUE TITLE
doesn't work with explicit dependencies

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_inline_test#29]
I'm getting this error:

```
Error: Unbound module Inline_test_config
```

when using `(implicit_transitive_deps false)`

see https://github.com/mimoo/hexstring/pull/4/files

**Comment by sliquister** [comment]
I think you could work around this by adding `ppx_inline_test.config` as a library dependency as well, if you prefer.

I submitted what I think is a fix for this for review (stating that both `ppx_inline_test.config` is a runtime dependency of the ppx), although I didn't confirm it's a fix.

**Comment by aalekseyev** [comment]
The fix landed in ff5b1a4.
