### ISSUE TITLE
Tests inside of module expression inside of function are ignored

### ISSUE THREAD

**Issue by copy** [janestreet/ppx_inline_test#31]
For example:

```ocaml
let foo () =
  let module _ = struct
    let%test _ = false
  end
  in ()
```

This is a fairly weird case, and I wouldn't expect it to work, however there should at least be an error rather than silently ignoring the tests.

**Comment by sliquister** [comment]
These tests are not ignored. The documentation says:

> When running tests, they will be executed when the control flow reaches the structure item (i.e. at toplevel for a toplevel test; when the functor is applied for a test defined in the body of a functor, etc.).

I agree that it can be surprising, but I'm pretty sure people do use this, so that can't be an error.

**Comment by copy** [comment]
Makes sense, cheers!
