### ISSUE TITLE
command line arguments

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_inline_test#32]
From the README: https://github.com/janestreet/ppx_inline_test#command-line-arguments it is not clear how to pass these command line arguments when working with dune.

I've tried the following but nothing worked

```
dune runtest -only-test FILE
dune runtest -- -only-test FILE
```

**Comment by sliquister** [comment]
Looking at `dune runtest --help` and a bit of the doc, my guess is that dune just doesn't support passing arguments to the runner (not just `ppx_inline_test`).
I think there are two options:
- maybe it's possible to get the inline tests runner from the _build directory, and run that (doesn't seem convenient though)
- you can edit the dune file temporarily to add the flags (see [doc](https://dune.readthedocs.io/en/stable/tests.html#passing-special-arguments-to-the-test-runner))
- you can report this in dune
