### ISSUE TITLE
"Error: ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)"

### ISSUE THREAD

**Issue by olleharstedt** [janestreet/ppx_inline_test#35]
Heyo, what actions should be taken upon the following error message?

> "Error: ppx_inline_test: extension is disabled because the tests would be ignored (the build system didn't pass -inline-test-lib)"

My environment:

The OCaml toplevel, version 4.14.0
opam 2.1.2
dune 3.4.1

**Comment by olleharstedt** [comment]
Hm, I got this to work, but only in the lib/ folder of the dune init project structure, not in the test/ folder.

**Comment by sliquister** [comment]
It only makes sense to set up tests for library stanzas, not executable stanzas as I suspect you tried to do, as otherwise running tests would just run your executable.

I'll tweak the error, but either way if you want inline tests, you should use a library stanza.
