### ISSUE TITLE
Configuration to stop at first failure

### ISSUE THREAD

**Issue by olleharstedt** [janestreet/ppx_inline_test#36]
Sometimes it's useful to stop at test run at the first failure, instead of getting a list of all error.

1) When all tests break because of a small change, the first failure might be the most interesting one
2) In a CI, you might not want to waste CPU resources after the first failure, especially when the test suit takes many minutes to complete fully

Compare with PHPUnit `--stop-on-failure`.

**Comment by sliquister** [comment]
Pass -help to the inline test runner script, and you'll see the flag already exists: -stop-on-error. `(inline_tests (flags (-stop-on-error))` in the library stanza should do the trick.
