### ISSUE TITLE
[%name ...] returns an error (constant expected)

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_inline_test#38]
```
2845 |         let%test [%name x ^ y] =
                        ^^^^^^^^^^^^^
Error: constant expected
```

where `x` and `y` are strings

**Comment by mimoo** [comment]
maybe I don't have the right version of ppx_inline_test?

```
❯ dune installed-libraries | grep inline
core_bench.inline_benchmarks              (version: v0.14.0)
ppx_inline_test                           (version: v0.14.0)
ppx_inline_test.config                    (version: v0.14.0)
ppx_inline_test.drop                      (version: v0.14.0)
ppx_inline_test.libname                   (version: v0.14.0)
ppx_inline_test.runner                    (version: v0.14.0)
ppx_inline_test.runner.lib                (version: v0.14.0)
ppx_inline_test.runtime-lib               (version: v0.14.0)
```

I'm trying to find a version number in `ppx_inline_test.opam` in this repo but nothing I can find

**Comment by mimoo** [comment]
Maybe I'm missing one of the sub module of ppx_inline_test as dependency in my `dune` file? I'm checking where `[%name]` is defined by grepping `register_transformation` but I can't find it

**Comment by mimoo** [comment]
maybe I'm missing an `open _` but the example doesn't seem to have one: https://github.com/janestreet/ppx_inline_test/blob/5f85f88a8eecf8a07e484a5c2e4bd5be32595d10/test/failures.ml#L29

**Comment by mimoo** [comment]
giving up now, not sure what is going on o.o

**Comment by sliquister** [comment]
This is the branch for the version you're using: https://github.com/janestreet/ppx_inline_test/tree/v0.14#readme . The README doesn't talk about `[%name ...]`.

This is the latest version in opam: https://github.com/janestreet/ppx_inline_test/tree/v0.15#readme. This one does mention `[%name ...]`.

So yeah, you need to use a newer version.

**Comment by mimoo** [comment]
thanks!
