### ISSUE TITLE
Debugging 0 tests

### ISSUE THREAD

**Issue by superbobry** [janestreet/ppx_inline_test#4]
Is there a way to debug test discovery? I have a separate executable for running tests, but once I run it, no tests are actually executed. 

The repository is available [here](https://github.com/superbobry/roaring). To reproduce the issue do:

```
$ make test
# ...
0 tests ran, 0 test_modules ran
```

**Comment by diml** [comment]
Maybe try adding the linkall tag on the test executable. The library modules are probably not linked in because the main module of the executable doesn't reference the lib

**Comment by superbobry** [comment]
Thanks, that was indeed the issue.
