### ISSUE TITLE
Warning: overriding the purity of the primitive Base_am_testing: pure -> mutator

### ISSUE THREAD

**Issue by mooreryan** [janestreet/ppx_inline_test#47]
When running expect tests/inline tests I get the following warning: `Warning: overriding the purity of the primitive Base_am_testing: pure -> mutator`.  Is this a warning that I need to worry about or address?

---

Here is an example.

`dune`

```
(library
 (name hello)
 (inline_tests
  (modes js))
 (preprocess
  (pps ppx_expect)))
```

`dune-project`

```
(lang dune 3.8)
```

`hello.ml`

```ocaml
let%expect_test _ = print_endline "hi" ; [%expect {| hi |}]
```

Running the tests

```
$ dune runtest
Warning: overriding the purity of the primitive Base_am_testing: pure -> mutator
```

Package versions:

- base v0.15.1
- dune 3.8.1
- js_of_ocaml 5.2.0
- ocaml 4.14.0
- ppx_expect v0.15.1
- ppx_inline_test v0.15.1

**Comment by hhugo** [comment]
Nothing to worry about.
It has been fixed in https://github.com/janestreet/ppx_inline_test/commit/1de4534f891ae7a398bca43354bd10de61908747

**Comment by mooreryan** [comment]
Thanks!
