### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by rgrinberg** [janestreet/ppx_inline_test#6]
The latest ppx_inline_test removes the `Ppx_inline_test_lib.Runtime.Test_result.record` function and it would be great if this was documented in the changelog. Preferably with a few words on how to migrate.

**Comment by rgrinberg** [comment]
It seems like the update wasn't done fully perhaps? For example this deprecation message:

https://github.com/janestreet/ppx_inline_test/blob/f4e97ae6dc3ed25e223e3887a1bf3c97b9b2e6a1/runtime-lib/runtime.mli#L22-L23

Refers to a function I don't see defined anywhere:

https://github.com/search?q=org%3Ajanestreet+eval_all_and_exit&type=Code

**Comment by diml** [comment]
Sorry about that, I didn't know this API was used. I added a comment in the changelog and updated the `[@@deprecated]` attribute

**Comment by rgrinberg** [comment]
Thanks!
