### ISSUE TITLE
Add instructions for using with jbuilder

### ISSUE THREAD

**Issue by basus** [janestreet/ppx_inline_test#8]
Currently the documentation only describes how to use this library with `jenga` or `ocamlbuild`. Since `jbuilder` seems to be gaining steam as a popular build system for the OCaml ecosystem, it would be great to have some guidance on how to build inline tests with it.

**Comment by bmillwood** [comment]
(You're already aware of this, but this is related to janestreet/jbuilder#65)

**Comment by braibant** [comment]
Finally managed to make this work: 

jbuild:
```
(library
 ((name foo)
  (public_name foo)
  (library_flags (-linkall))
  (libraries (base ppx_inline_test.runtime-lib))
  (preprocess (pps (ppx_inline_test ppx_driver.runner)))
  )
 )

(executable
 ((name test_runner)
  (modules (test_runner))
  (libraries (foo ppx_inline_test.runner.lib))))

(alias
 ((name    runtest)
  (deps    (test_runner.exe))
  (action  (run ${<} inline-test-runner foo))))
```

With test_runner.ml:
```
Ppx_inline_test_lib.Runtime.exit ()
```

**Comment by hhugo** [comment]
waitting for https://github.com/janestreet/jbuilder/pull/338

**Comment by psteckler** [comment]
> Finally managed to make this work:

Doing something similar with my own library and test driver, I get an error message:
```
You are doing something unexpected with the tests. No tests have 
been run. You should use the inline_tests_runner script to run 
tests.
```
What step am I missing?

**Comment by psteckler** [comment]
@leviroth Yep, that works here. Thanks!
